# Generated by Django 3.0.2 on 2020-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.IntegerField(blank=True)),
                ('teamAId', models.IntegerField(blank=True)),
                ('teamBId', models.IntegerField(blank=True)),
                ('locationId', models.IntegerField(blank=True)),
                ('date', models.IntegerField(blank=True)),
                ('prebookedId', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerId', models.IntegerField(blank=True)),
                ('Position', models.IntegerField(blank=True)),
                ('manifesto', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamId', models.IntegerField(blank=True)),
                ('queueJoinTime', models.IntegerField(blank=True)),
                ('allocatedTime', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CupDraws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawID', models.IntegerField(blank=True)),
                ('teamAId', models.IntegerField(blank=True)),
                ('teamBId', models.IntegerField(blank=True)),
                ('cupRoundId', models.IntegerField(blank=True)),
                ('teamAgoals', models.IntegerField(blank=True)),
                ('teamBgoals', models.IntegerField(blank=True)),
                ('resultId', models.IntegerField(blank=True)),
                ('locationId', models.IntegerField(blank=True)),
                ('prebookedid', models.IntegerField(blank=True)),
                ('date', models.IntegerField(blank=True)),
                ('confirmed', models.IntegerField(blank=True)),
                ('deadline', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CupRounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupRoundId', models.IntegerField(blank=True)),
                ('startDate', models.IntegerField(blank=True)),
                ('endDate', models.IntegerField(blank=True)),
                ('cupRoundTitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixtureId', models.IntegerField(blank=True)),
                ('locationId', models.IntegerField(blank=True)),
                ('challengedTeamId', models.IntegerField(blank=True)),
                ('resultId', models.IntegerField(blank=True)),
                ('confirmed', models.IntegerField(blank=True)),
                ('date', models.IntegerField(blank=True)),
                ('challengingTeamGoals', models.IntegerField(blank=True)),
                ('challengedTeamGoals', models.IntegerField(blank=True)),
                ('prebookedId', models.IntegerField(blank=True)),
                ('challengingGoalsEntered', models.IntegerField(blank=True)),
                ('challengedGoalsEntered', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leagueId', models.IntegerField(blank=True)),
                ('teamId', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueFinals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.IntegerField(blank=True)),
                ('teamAid', models.IntegerField(blank=True)),
                ('teamBId', models.IntegerField(blank=True)),
                ('teamAGoals', models.IntegerField(blank=True)),
                ('teamBGoals', models.IntegerField(blank=True)),
                ('resultId', models.IntegerField(blank=True)),
                ('date', models.IntegerField(blank=True)),
                ('locationId', models.IntegerField(blank=True)),
                ('prebookedId', models.IntegerField(blank=True)),
                ('roundId', models.IntegerField(blank=True)),
                ('typeId', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.IntegerField(blank=True)),
                ('teamAid', models.IntegerField(blank=True)),
                ('teamBId', models.IntegerField(blank=True)),
                ('teamAGoals', models.IntegerField(blank=True)),
                ('teamBGoals', models.IntegerField(blank=True)),
                ('resultId', models.IntegerField(blank=True)),
                ('date', models.IntegerField(blank=True)),
                ('locationId', models.IntegerField(blank=True)),
                ('prebookedId', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationId', models.IntegerField(blank=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('pitches', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PitchBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.IntegerField(blank=True)),
                ('teamAId', models.IntegerField(blank=True)),
                ('teamBId', models.IntegerField(blank=True)),
                ('locationId', models.IntegerField(blank=True)),
                ('date', models.IntegerField(blank=True)),
                ('prebooked', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionId', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PreBooked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prebookedId', models.IntegerField(blank=True)),
                ('locationId', models.IntegerField(blank=True)),
                ('day', models.IntegerField(blank=True)),
                ('time', models.IntegerField(blank=True)),
                ('temp', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=220)),
                ('password', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='teamsImage/')),
                ('ladderId', models.IntegerField(blank=True)),
                ('competitionId', models.IntegerField(blank=True)),
                ('position', models.IntegerField(blank=True)),
                ('contactforfriendly', models.IntegerField(blank=True)),
                ('seeded', models.IntegerField(blank=True)),
                ('coefficient', models.IntegerField(blank=True)),
                ('coefficientRank', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.IntegerField(blank=True)),
                ('candidateId', models.IntegerField(blank=True)),
                ('date', models.DateField(blank=True, max_length=5)),
                ('positionId', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='fb_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='goalsScored',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='isExec',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='password',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='public_details',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='send_email',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='sessionKey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='studentId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='teamID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='webmaster',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='displayName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
