# Generated by Django 3.0.2 on 2020-08-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0002_auto_20200813_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='challengingTeamId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
