# Generated by Django 3.0.2 on 2020-08-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0003_fixtures_challengingteamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='teamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Teams'),
        ),
    ]
