# Generated by Django 3.0.2 on 2020-08-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0005_auto_20200813_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitchbookings',
            name='prebooked',
        ),
        migrations.AddField(
            model_name='pitchbookings',
            name='prebookedId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.PreBooked'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='positionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Positions'),
        ),
        migrations.AlterField(
            model_name='cupdraws',
            name='cupRoundId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.CupRounds'),
        ),
        migrations.AlterField(
            model_name='cupdraws',
            name='locationId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Locations'),
        ),
        migrations.AlterField(
            model_name='cupdraws',
            name='prebookedid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.PreBooked'),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='challengedTeamId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChallengedTeam', to='Databasetables.Teams'),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='challengingTeamId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Teams'),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='locationId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Locations'),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='prebookedId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.PreBooked'),
        ),
        migrations.AlterField(
            model_name='league',
            name='teamId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Teams'),
        ),
        migrations.AlterField(
            model_name='leaguefinals',
            name='locationId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Locations'),
        ),
        migrations.AlterField(
            model_name='leaguefinals',
            name='prebookedId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.PreBooked'),
        ),
        migrations.AlterField(
            model_name='leaguefinals',
            name='teamAid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Teams'),
        ),
        migrations.AlterField(
            model_name='leaguefinals',
            name='teamBId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TeamBLeagueFinal', to='Databasetables.Teams'),
        ),
        migrations.AlterField(
            model_name='leaguegames',
            name='locationId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Locations'),
        ),
        migrations.AlterField(
            model_name='leaguegames',
            name='prebookedId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.PreBooked'),
        ),
        migrations.AlterField(
            model_name='leaguegames',
            name='teamAid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Teams'),
        ),
        migrations.AlterField(
            model_name='leaguegames',
            name='teamBId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TeamBLeagueGames', to='Databasetables.Teams'),
        ),
        migrations.AlterField(
            model_name='pitchbookings',
            name='bookingId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Booking'),
        ),
        migrations.AlterField(
            model_name='pitchbookings',
            name='locationId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Locations'),
        ),
        migrations.AlterField(
            model_name='pitchbookings',
            name='teamAId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Teams'),
        ),
        migrations.AlterField(
            model_name='pitchbookings',
            name='teamBId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TeamBPitchBookings', to='Databasetables.Teams'),
        ),
    ]
