# Generated by Django 3.0.2 on 2020-08-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0010_prebooked_prebookedid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prebooked',
            name='prebookedId',
        ),
    ]
