# Generated by Django 3.0.2 on 2020-08-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0011_remove_prebooked_prebookedid'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='locationId',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
