# Generated by Django 3.0.2 on 2020-08-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0012_locations_locationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='locationId',
        ),
    ]
