# Generated by Django 3.0.2 on 2020-08-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0013_remove_locations_locationid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='playerid',
            new_name='playerId',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='candidateId',
        ),
        migrations.AlterField(
            model_name='cupdraws',
            name='date',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
