# Generated by Django 3.0.2 on 2020-08-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0014_auto_20200817_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='leagueId',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
