# Generated by Django 3.0.2 on 2020-08-17 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Databasetables', '0015_league_leagueid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField()),
                ('isExcec', models.CharField(default='0', max_length=10)),
                ('phone', models.IntegerField(blank=True, default='0')),
                ('send_email', models.IntegerField(blank=True, default='0', null=True)),
                ('fb_id', models.CharField(blank=True, max_length=5, null=True)),
                ('goalsScored', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
