# Generated by Django 3.0.2 on 2020-08-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0016_playerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Teams'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='playerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.PlayerProfile'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='playerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.PlayerProfile'),
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
