# Generated by Django 3.0.2 on 2020-08-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0017_auto_20200817_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguefinals',
            old_name='teamAid',
            new_name='teamAId',
        ),
        migrations.RenameField(
            model_name='leaguegames',
            old_name='teamAid',
            new_name='teamAId',
        ),
        migrations.RemoveField(
            model_name='pitchbookings',
            name='bookingId',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
