# Generated by Django 3.0.2 on 2020-08-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0018_auto_20200817_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='phone',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='studentId',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='teams',
            name='photo',
            field=models.FileField(blank=True, upload_to='teamsImage/'),
        ),
    ]
