# Generated by Django 3.0.2 on 2020-08-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0019_auto_20200823_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='fb_id',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='goalsScored',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='isExcec',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='send_email',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
