# Generated by Django 3.0.2 on 2020-08-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0020_auto_20200823_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='team',
        ),
    ]
