# Generated by Django 3.0.2 on 2020-08-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0022_auto_20200825_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupdraws',
            old_name='prebookedid',
            new_name='prebookedId',
        ),
    ]
