# Generated by Django 3.0.2 on 2020-08-27 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0023_auto_20200827_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Teams'),
        ),
    ]
