# Generated by Django 3.0.2 on 2020-09-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0024_playerprofile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebooked',
            name='locationId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Locations'),
        ),
    ]
