# Generated by Django 3.0.2 on 2020-09-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0027_auto_20200905_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='ladderId',
            field=models.IntegerField(blank=True),
        ),
    ]
