# Generated by Django 3.0.2 on 2020-09-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0028_auto_20200905_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='description',
            field=models.TextField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='teams',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
