# Generated by Django 3.0.2 on 2020-09-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0031_auto_20200906_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='goals_scored',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='phone',
        ),
    ]
