# Generated by Django 3.0.2 on 2020-09-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0032_auto_20200906_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Databasetables.Teams'),
        ),
    ]
