# Generated by Django 3.0.2 on 2020-09-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0038_auto_20200919_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='ladderId',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
