# Generated by Django 3.0.2 on 2020-09-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0043_auto_20200919_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='ladderId',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
