# Generated by Django 3.0.2 on 2020-09-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0045_auto_20200919_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
