# Generated by Django 3.0.2 on 2020-09-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0046_playerprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='email',
        ),
    ]
