# Generated by Django 3.0.2 on 2020-09-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0047_remove_playerprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='fb_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='goalsScored',
            field=models.IntegerField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='phone',
            field=models.IntegerField(blank=True, default='0', max_length=11),
        ),
        migrations.DeleteModel(
            name='PlayerTeam',
        ),
    ]
