# Generated by Django 3.0.2 on 2020-09-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databasetables', '0048_auto_20200920_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='goalsScored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='phone',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
